---
title: "team.Rmd"
author: "Mike Brown and Nathan Marquardt"
date: "3/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1.Find the average years of education of he respondents with each marital status. Arrange your output in a meaningful order and print. Describe any patterns you find. 

  Answer:

2.Create a single data frame containing records for the better educated respondents with each marital status. A "better educated" respondent is someone who has strictly more years of education than the average among those with the same marital status. Print the structure of the data frame. 

  Answer:
  
**For each of the investigation below, create at least one nemerical summary and one appropriate visualization. Write a paragraph to describe your findings and the variables you used.**

3.How is the happiness of a respondent related to his/her marriage status? Define that a person is happy if the resonse to question is "Very happy" or "Pretty happy".

  Answer:

4.Does party affiliation affect the relationship you found in the last question?

  Answer:

5.How is marital status related to the education of a respondent? What are possible reasons accounting for the patterns you see?

  Answer:

6.Explore two more interesting questions, and answer those questions using the GSS data. 

  Answer:
